# @name playerOne
POST {{host}}/auth/local

###

@playerOneAuth = Cookie: {{playerOne.response.headers.Set-Cookie}}

GET {{host}}/user/info
{{playerOneAuth}}

###

DELETE {{host}}/auth
{{playerOneAuth}}

###

# @name playerTwo
POST {{host}}/auth/local

###
@playerTwoAuth = Cookie: {{playerTwo.response.headers.Set-Cookie}}

GET {{host}}/user/info
{{playerTwoAuth}}

###
DELETE {{host}}/auth
{{playerTwoAuth}}

###

# @name startOne
POST {{host}}/game/start
{{playerOneAuth}}

###

# @name startTwo
POST {{host}}/game/start
{{playerTwoAuth}}

###

# @name waitingOne
GET {{host}}/game/waiting
{{playerOneAuth}}

###

# @name waitingTwo
GET {{host}}/game/waiting
{{playerTwoAuth}}

###

# @name moveOne
GET {host}/game/moves/row/1/column/1
{{playerOneAuth}}

# rows begin at 1 at the bottom; columns begin at 1 at the left
# 400 if bad coordinates
# 400 if piece is not yours
# 200 type Coordinate = { row: number; column: number; }
# 200 type Tree = { root: Coordinate; branches: Tree[] }
# 200 type Body = Tree
# 200 [{"root": {"row": 3, "column": 3}, "branches": [ ]}]

###

# @name moveTwo
POST {{host}}/game/move
{{playerOneAuth}}

{
    "from": {"row": 1, "column": 1},
    "to": {
        "root": {"row": 3, "column": 3},
        "path": []
    }
}

# rows begin at 1 at the bottom; columns begin at 1 at the left
# 400 if bad coordinates
# 400 if piece is not yours
# 200 type Coordinate = { row: number; column: number; }
# 200 type Path = Coordinate[]
# 200 type Body = {"from": Coordinate, "to": {"root": Coordinate; "path": Coordinate[]}}
# 200 [{"root": {"row": 3, "column": 3}, "branches": [ ]}]