# @name playerOne
POST {{host}}/auth/local

###

@playerOneAuth = Cookie: {{playerOne.response.headers.Set-Cookie}}

GET {{host}}/user/info
{{playerOneAuth}}

###

DELETE {{host}}/auth
{{playerOneAuth}}

###

# @name playerTwo
POST {{host}}/auth/local

###
@playerTwoAuth = Cookie: {{playerTwo.response.headers.Set-Cookie}}

GET {{host}}/user/info
{{playerTwoAuth}}

###
DELETE {{host}}/auth
{{playerTwoAuth}}

###

# @name startOne
POST {{host}}/game/start
{{playerOneAuth}}

###

# @name startTwo
POST {{host}}/game/start
{{playerTwoAuth}}

###

# @name waitingOne
GET {{host}}/game/waiting
{{playerOneAuth}}

###

# @name waitingTwo
GET {{host}}/game/waiting
{{playerTwoAuth}}

###

# @name moveOne
POST {host}/game/move
{{playerOneAuth}}

{"from": {"row":3 ,"col":0},
"to":{"row":6,"col":2}}
###

# @name moveTwo
POST {{host}}/game/move
{{playerTwoAuth}}

{"from": {"row":2 ,"col":0},
"to":{"row":4,"col":2}}