POST  http://localhost:5000/start-game


###
POST  http://localhost:5000/start-game

{}


###
POST  http://localhost:5000/start-game
Content-Type: application/json

{"email": "jay@mail.usf.edu", "name": "jay" }