# @name auth
POST {{host}}/auth/local
Content-Type: application/json

{
    "id": "test"
}
###

GET {{host}}/user
Cookie: {{auth.response.headers.set-cookie}}

###

POST {{host}}/user/upgrade
Content-Type: application/json
Cookie: {{auth.response.headers.set-cookie}}

{
    "stripeEmail": "spencer@palmbeachsoftware.com",
    "stripeToken": "12345"
}

###

DELETE {{host}}/user/upgrade
Cookie: {{auth.response.headers.set-cookie}}